### ISSUE TITLE
URL compatibile con Image (companion app)

### ISSUE THREAD

**Issue by jokerigno** [caiosweet/Package-Notification-HUB-AppDaemon#24]
Ciao,

ho questa automazione che funziona se come text notification uso telegram:

```
service: script.my_notify
data:
  call_no_annuncio: 1
  title: Telecamere
  google: true
  message: >-
    Una persona è stata rilevata in {{ trigger.payload_json['after']['camera']
    }}.
  url: >-
    http://192.168.2.100:5000/api/events/{{trigger.payload_json["after"]["id"]}}/thumbnail.jpg
  caption: >-
    Una persona è stata rilevata in {{ trigger.payload_json['after']['camera']
    }} alle ore {{ states('sensor.time_date') }}
```
Mentre non funziona se uso come text notification notify.mioiphone.

O meglio funziona il message ma non l'url.

Leggendo i docs della companion app ho visto che sono state da poco rimaneggiate uniformando ios e android. Per l'invio delle immagini usano "image" con questa struttura:

```
service: notify.mioiphone
data:
  message: "Una persona è stata rilevata in prova"
  data:
    # an example of an absolute url
    image: "http://192.168.2.100:5000/clips/veranda-1625310307.36589-sf2mpx.jpg"
```
Se però sostitusco notify.mioiphone con script.my_notify non ricevo l'immagine.

E' possibile uniformarlo?
